In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math
import random as rd
frame = pd.read_csv('mcdonalds.csv', usecols=['Item', 'Category', 'Serving Size', 'Calories', 'TotalFat'])

In [2]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [3]:
has400CalOrMore = frame['Calories'] >= 400

In [4]:
frame.where(has400CalOrMore).head()

,Category,Item,Serving Size,Calories,TotalFat
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0

In [5]:
frame.query('Category == "Desserts"').head()

     Category                   Item     Serving Size  Calories  TotalFat
103  Desserts        Baked Apple Pie    2.7 oz (77 g)       250      13.0
104  Desserts  Chocolate Chip Cookie  1 cookie (33 g)       160       8.0
105  Desserts  Oatmeal Raisin Cookie  1 cookie (33 g)       150       6.0
106  Desserts    Kids Ice Cream Cone      1 oz (29 g)        45       1.5
107  Desserts       Hot Fudge Sundae   6.3 oz (179 g)       330       9.0