In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math
import random as rd
from datetime import datetime
from datetime import timedelta
import time

In [2]:
products = pd.read_csv("WA_Sales_Products_2012-14.csv")

In [3]:
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

In [4]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88475 entries, 0 to 88474
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Retailer country   88475 non-null  object
 1   Order method type  88475 non-null  object
 2   Retailer type      88475 non-null  object
 3   Product line       88475 non-null  object
 4   Product type       88475 non-null  object
 5   Product            88475 non-null  object
 6   Year               88475 non-null  int64
 7   Quarter            88475 non-null  object
 8   Revenue            88475 non-null  float64
 9   Quantity           88475 non-null  int64
 10  Gross margin       87894 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 7.4+ MB

In [5]:
products.describe()

               Year       Revenue      Quantity  Gross margin
count  88475.000000  8.847500e+04  88475.000000  87894.000000
mean    2012.855281  4.263829e+04    780.586166      0.449718
std        0.778342  6.578402e+04   1541.645422      0.123642
min     2012.000000  0.000000e+00      1.000000    -12.853678
25%     2012.000000  8.184360e+03    131.000000      0.369880
50%     2013.000000  2.102628e+04    333.000000      0.450634
75%     2013.000000  5.039060e+04    816.000000      0.520130
max     2014.000000  1.635688e+06  67875.000000      0.770476

In [6]:
products['Retailer country'].value_counts()

United States     7482
Canada            5923
France            5779
Germany           5397
Japan             5359
United Kingdom    5102
Netherlands       4199
Switzerland       4103
Italy             4018
Austria           3862
Mexico            3845
Belgium           3710
Australia         3665
China             3652
Spain             3557
Singapore         3443
Finland           3409
Korea             3399
Brazil            3288
Sweden            2925
Denmark           2358
Name: Retailer country, dtype: int64

In [7]:
products['Retailer country'].nunique()

21

In [8]:
countries = products['Retailer country'].unique()

In [9]:
countries

array(['United States', 'Canada', 'Mexico', 'Brazil', 'Japan',
       'Singapore', 'Korea', 'China', 'Australia', 'Netherlands',
       'Sweden', 'Denmark', 'Finland', 'France', 'Germany', 'Switzerland',
       'United Kingdom', 'Belgium', 'Austria', 'Italy', 'Spain'],
      dtype=object)

In [12]:
for country in countries:
    myOwnSubDataFrame = products.where(products['Retailer country'] == country).dropna()
    myOwnGroups[country] = myOwnSubDataFrame

In [11]:
myOwnGroups = {}

In [13]:
myOwnGroups

{'United States':       Retailer country Order method type  Retailer type          Product line  \
 0        United States               Fax  Outdoors Shop     Camping Equipment
 1        United States               Fax  Outdoors Shop     Camping Equipment
 2        United States               Fax  Outdoors Shop     Camping Equipment
 3        United States               Fax  Outdoors Shop     Camping Equipment
 4        United States               Fax  Outdoors Shop     Camping Equipment
 ...                ...               ...            ...                   ...
 84049    United States       Sales visit  Eyewear Store  Personal Accessories
 84050    United States       Sales visit  Eyewear Store  Personal Accessories
 84051    United States       Sales visit  Eyewear Store  Personal Accessories
 84052    United States       Sales visit  Eyewear Store  Personal Accessories
 84053    United States       Sales visit  Eyewear Store  Personal Accessories

         Product type                    Product    Year  Quarter    Revenue  \
 0       Cooking Gear  TrailChef Deluxe Cook Set  2012.0  Q1 2012   59628.66
 1       Cooking Gear     TrailChef Double Flame  2012.0  Q1 2012   35950.32
 2              Tents                  Star Dome  2012.0  Q1 2012   89940.48
 3              Tents               Star Gazer 2  2012.0  Q1 2012  165883.41
 4      Sleeping Bags            Hibernator Lite  2012.0  Q1 2012  119822.20
 ...              ...                        ...     ...      ...        ...
 84049        Eyewear                  Polar Ice  2014.0  Q3 2014   20957.00
 84050        Eyewear               Polar Sports  2014.0  Q3 2014  105495.85
 84051        Eyewear                 Polar Wave  2014.0  Q3 2014    6540.48
 84052        Eyewear              Polar Extreme  2014.0  Q3 2014    6340.05
 84053     Binoculars                  Seeker 35  2014.0  Q3 2014   83324.99

        Quantity  Gross margin
 0         489.0      0.347548
 1         252.0      0.474274
 2         147.0      0.352772
 3         303.0      0.282938
 4        1415.0      0.291450
 ...         ...           ...
 84049     218.0      0.483112
 84050     905.0      0.494896
 84051      72.0      0.547336
 84052      45.0      0.485414
 84053     833.0      0.288314

 [7449 rows x 11 columns],
 'Canada':       Retailer country Order method type  Retailer type          Product line  \
 864             Canada               Fax  Outdoors Shop  Personal Accessories
 865             Canada               Fax  Outdoors Shop  Personal Accessories
 866             Canada               Fax  Outdoors Shop  Personal Accessories
 867             Canada               Fax  Outdoors Shop  Personal Accessories
 868             Canada               Fax  Outdoors Shop  Personal Accessories
 ...                ...               ...            ...                   ...
 84363           Canada               Web   Sports Store        Golf Equipment
 84364           Canada               Web   Sports Store        Golf Equipment
 84365           Canada               Web   Sports Store        Golf Equipment
 84366           Canada               Web   Sports Store        Golf Equipment
 84367           Canada               Web   Sports Store        Golf Equipment

            Product type                Product    Year  Quarter   Revenue  \
 864             Watches                  Venue  2012.0  Q1 2012  12045.00
 865             Watches                     TX  2012.0  Q1 2012  20960.00
 866             Watches                 Legend  2012.0  Q1 2012   3740.00
 867             Watches                 Kodiak  2012.0  Q1 2012  33445.20
 868             Eyewear                  Capri  2012.0  Q1 2012  23784.30
 ...                 ...                    ...     ...      ...       ...
 84363           Putters      Course Pro Putter  2014.0  Q3 2014  68133.45
 84364           Putters  Blue Steel Max Putter  2014.0  Q3 2014  37408.80
 84365  Golf Accessories    Course Pro Umbrella  2014.0  Q3 2014  14356.65
 84366  Golf Accessories    Course Pro Golf Bag  2014.0  Q3 2014  24167.44
 84367  Golf Accessories      Course Pro Gloves  2014.0  Q3 2014  13753.76

        Quantity  Gross margin
 864       165.0      0.418630
 865       114.0      0.450544
 866        17.0      0.473455
 867       271.0      0.455317
 868       621.0      0.340707
 ...         ...           ...
 84363    1735.0      0.385281
 84364     218.0      0.523310
 84365    1155.0      0.479485
 84366     116.0      0.617452
 84367    2566.0      0.524254

 [5904 rows x 11 columns],
 'Mexico':       Retailer country Order method type Retailer type          Product line  \
 1468            Mexico               Web     Golf Shop  Personal Accessories
 1469            Mexico               Web     Golf Shop  Personal Accessories
 1470            Mexico               Web     Golf Shop  Personal Accessories
 1471            Mexico               Web     Golf Shop  Personal Accessories
 1472            Mexico               Web     Golf Shop  Personal Accessories
 ...                ...               ...           ...                   ...
 84551           Mexico               Web  Sports Store        Golf Equipment
 84552           Mexico               Web  Sports Store        Golf Equipment
 84553           Mexico               Web  Sports Store        Golf Equipment
 84554           Mexico               Web  Sports Store        Golf Equipment
 84555           Mexico               Web  Sports Store        Golf Equipment

            Product type                Product    Year  Quarter   Revenue  \
 1468            Watches               Infinity  2012.0  Q1 2012   4620.00
 1469            Watches                    Lux  2012.0  Q1 2012   5684.80
 1470            Watches                     TX  2012.0  Q1 2012   4888.00
 1471            Watches                 Legend  2012.0  Q1 2012   4593.40
 1472            Eyewear                  Capri  2012.0  Q1 2012   4825.80
 ...                 ...                    ...     ...      ...       ...
 84551           Putters      Course Pro Putter  2014.0  Q3 2014  79403.94
 84552           Putters      Blue Steel Putter  2014.0  Q3 2014  20655.95
 84553           Putters  Blue Steel Max Putter  2014.0  Q3 2014  45474.00
 84554  Golf Accessories    Course Pro Umbrella  2014.0  Q3 2014  17861.91
 84555  Golf Accessories      Course Pro Gloves  2014.0  Q3 2014  14804.32

        Quantity  Gross margin
 1468       21.0      0.474727
 1469       34.0      0.478828
 1470       26.0      0.451702
 1471       17.0      0.444782
 1472      126.0      0.340209
 ...         ...           ...
 84551    2022.0      0.385281
 84552     245.0      0.511327
 84553     265.0      0.523310
 84554    1437.0      0.479485
 84555    2762.0      0.524254

 [3818 rows x 11 columns],
 'Brazil':       Retailer country Order method type Retailer type          Product line  \
 1833            Brazil               Web     Golf Shop  Personal Accessories
 1834            Brazil               Web     Golf Shop  Personal Accessories
 1835            Brazil               Web     Golf Shop  Personal Accessories
 1836            Brazil               Web     Golf Shop  Personal Accessories
 1837            Brazil               Web     Golf Shop  Personal Accessories
 ...                ...               ...           ...                   ...
 84734           Brazil               Web  Sports Store        Golf Equipment
 84735           Brazil               Web  Sports Store        Golf Equipment
 84736           Brazil               Web  Sports Store        Golf Equipment
 84737           Brazil               Web  Sports Store        Golf Equipment
 84738           Brazil               Web  Sports Store        Golf Equipment

            Product type                Product    Year  Quarter   Revenue  \
 1833            Watches                  Venue  2012.0  Q1 2012  15987.00
 1834            Watches                    Lux  2012.0  Q1 2012   7189.60
 1835            Watches                    Sam  2012.0  Q1 2012   8890.20
 1836            Watches                     TX  2012.0  Q1 2012  17816.00
 1837            Watches                 Kodiak  2012.0  Q1 2012   7218.00
 ...                 ...                    ...     ...      ...       ...
 84734           Putters      Blue Steel Putter  2014.0  Q3 2014  12309.26
 84735           Putters  Blue Steel Max Putter  2014.0  Q3 2014  23509.20
 84736  Golf Accessories    Course Pro Umbrella  2014.0  Q3 2014  10391.40
 84737  Golf Accessories    Course Pro Golf Bag  2014.0  Q3 2014  18750.60
 84738  Golf Accessories      Course Pro Gloves  2014.0  Q3 2014   8066.80

        Quantity  Gross margin
 1833      219.0      0.419206
 1834       43.0      0.478828
 1835      198.0      0.388419
 1836       93.0      0.458950
 1837       60.0      0.444223
 ...         ...           ...
 84734     146.0      0.511327
 84735     137.0      0.523310
 84736     828.0      0.484462
 84737      90.0      0.617452
 84738    1505.0      0.524254

 [3273 rows x 11 columns],
 'Japan':       Retailer country Order method type  Retailer type  \
 2146             Japan               Fax  Outdoors Shop
 2147             Japan               Fax  Outdoors Shop
 2148             Japan               Fax  Outdoors Shop
 2149             Japan               Fax  Outdoors Shop
 2150             Japan               Fax  Outdoors Shop
 ...                ...               ...            ...
 85074            Japan       Sales visit   Sports Store
 85075            Japan       Sales visit   Sports Store
 85076            Japan       Sales visit   Sports Store
 85077            Japan       Sales visit   Sports Store
 85078            Japan       Sales visit   Sports Store

                    Product line      Product type                Product  \
 2146          Camping Equipment      Cooking Gear    TrailChef Water Bag
 2147          Camping Equipment      Cooking Gear     TrailChef Utensils
 2148          Camping Equipment          Lanterns        Firefly Extreme
 2149          Camping Equipment          Lanterns        EverGlow Single
 2150   Mountaineering Equipment              Rope          Husky Rope 50
 ...                         ...               ...                    ...
 85074      Personal Accessories        Navigation            Glacier GPS
 85075            Golf Equipment             Irons  Hailstorm Steel Irons
 85076            Golf Equipment           Putters      Course Pro Putter
 85077            Golf Equipment           Putters      Blue Steel Putter
 85078            Golf Equipment  Golf Accessories      Course Pro Gloves

          Year  Quarter   Revenue  Quantity  Gross margin
 2146   2012.0  Q1 2012  28009.45    7091.0      0.465823
 2147   2012.0  Q1 2012  17954.11     957.0      0.466974
 2148   2012.0  Q1 2012   7504.70     151.0      0.434205
 2149   2012.0  Q1 2012  15638.70     462.0      0.467061
 2150   2012.0  Q1 2012  19401.60     129.0      0.329056
 ...       ...      ...       ...       ...           ...
 85074  2014.0  Q3 2014  48623.85     517.0      0.308878
 85075  2014.0  Q3 2014  68320.20     156.0      0.495376
 85076  2014.0  Q3 2014  57373.47    1461.0      0.385281
 85077  2014.0  Q3 2014  15681.66     186.0      0.511327
 85078  2014.0  Q3 2014  12070.72    2252.0      0.524254

 [5308 rows x 11 columns],
 'Singapore':       Retailer country Order method type  Retailer type          Product line  \
 2750         Singapore               Fax  Outdoors Shop     Camping Equipment
 2751         Singapore               Fax  Outdoors Shop     Camping Equipment
 2752         Singapore               Fax  Outdoors Shop     Camping Equipment
 2753         Singapore               Fax  Outdoors Shop     Camping Equipment
 2754         Singapore               Fax  Outdoors Shop     Camping Equipment
 ...                ...               ...            ...                   ...
 85255        Singapore               Web  Outdoors Shop  Personal Accessories
 85256        Singapore               Web  Outdoors Shop  Personal Accessories
 85257        Singapore               Web  Outdoors Shop  Personal Accessories
 85258        Singapore               Web  Outdoors Shop  Personal Accessories
 85259        Singapore               Web  Outdoors Shop  Personal Accessories

         Product type                       Product    Year  Quarter   Revenue  \
 2750    Cooking Gear            TrailChef Cook Set  2012.0  Q1 2012  49777.12
 2751   Sleeping Bags             Hibernator Pillow  2012.0  Q1 2012   6539.40
 2752           Packs  Canyon Mule Climber Backpack  2012.0  Q1 2012  30995.25
 2753        Lanterns           Firefly Multi-light  2012.0  Q1 2012   6502.50
 2754        Lanterns               EverGlow Butane  2012.0  Q1 2012   6558.01
 ...              ...                           ...     ...      ...       ...
 85255     Binoculars                 Ranger Vision  2014.0  Q3 2014  56666.50
 85256     Navigation                Glacier Deluxe  2014.0  Q3 2014  22263.66
 85257     Navigation           Glacier GPS Extreme  2014.0  Q3 2014  75839.64
 85258     Navigation                   Astro Pilot  2014.0  Q3 2014  53919.00
 85259     Navigation                     Sky Pilot  2014.0  Q3 2014  10024.00

        Quantity  Gross margin
 2750      944.0      0.336810
 2751      378.0      0.529480
 2752      429.0      0.273356
 2753      250.0      0.316417
 2754      103.0      0.361866
 ...         ...           ...
 85255     337.0      0.533432
 85256     243.0      0.443353
 85257     222.0      0.483432
 85258     294.0      0.371835
 85259      28.0      0.358715

 [3420 rows x 11 columns],
 'Korea':       Retailer country Order method type Retailer type        Product line  \
 3074             Korea         Telephone  Sports Store   Camping Equipment
 3075             Korea         Telephone  Sports Store   Camping Equipment
 3076             Korea         Telephone  Sports Store   Camping Equipment
 3077             Korea         Telephone  Sports Store   Camping Equipment
 3078             Korea         Telephone  Sports Store   Camping Equipment
 ...                ...               ...           ...                 ...
 85443            Korea               Web  Sports Store      Golf Equipment
 85444            Korea               Web  Sports Store      Golf Equipment
 85445            Korea               Web  Sports Store      Golf Equipment
 85446            Korea               Web  Sports Store      Golf Equipment
 85447            Korea       Sales visit     Golf Shop  Outdoor Protection

            Product type                    Product    Year  Quarter   Revenue  \
 3074       Cooking Gear          TrailChef Canteen  2012.0  Q1 2012  12390.90
 3075       Cooking Gear  TrailChef Deluxe Cook Set  2012.0  Q1 2012  68896.10
 3076       Cooking Gear     TrailChef Single Flame  2012.0  Q1 2012  52655.64
 3077      Sleeping Bags            Hibernator Lite  2012.0  Q1 2012  65118.92
 3078           Lanterns                  Firefly 4  2012.0  Q1 2012   8972.55
 ...                 ...                        ...     ...      ...       ...
 85443           Putters      Blue Steel Max Putter  2014.0  Q3 2014  48391.20
 85444  Golf Accessories        Course Pro Umbrella  2014.0  Q3 2014  18433.69
 85445  Golf Accessories        Course Pro Golf Bag  2014.0  Q3 2014  31459.34
 85446  Golf Accessories          Course Pro Gloves  2014.0  Q3 2014  17730.88
 85447         Sunscreen                 Sun Shield  2014.0  Q3 2014   2292.00

        Quantity  Gross margin
 3074     1030.0      0.449709
 3075      565.0      0.347548
 3076      839.0      0.260994
 3077      769.0      0.291450
 3078      381.0      0.388535
 ...         ...           ...
 85443     282.0      0.523310
 85444    1483.0      0.479485
 85445     151.0      0.617452
 85446    3308.0      0.524254
 85447     382.0      0.540000

 [3373 rows x 11 columns],
 'China':       Retailer country Order method type Retailer type        Product line  \
 3403             China               Fax     Golf Shop      Golf Equipment
 3404             China               Fax     Golf Shop      Golf Equipment
 3405             China               Fax     Golf Shop      Golf Equipment
 3406             China               Fax     Golf Shop      Golf Equipment
 3407             China               Fax     Golf Shop      Golf Equipment
 ...                ...               ...           ...                 ...
 85667            China               Web  Sports Store  Outdoor Protection
 85668            China               Web  Sports Store  Outdoor Protection
 85669            China               Web  Sports Store  Outdoor Protection
 85670            China               Web  Sports Store  Outdoor Protection
 85671            China               Web  Sports Store  Outdoor Protection

             Product type                     Product    Year  Quarter  \
 3403               Irons       Hailstorm Steel Irons  2012.0  Q1 2012
 3404               Irons  Lady Hailstorm Steel Irons  2012.0  Q1 2012
 3405               Woods   Hailstorm Steel Woods Set  2012.0  Q1 2012
 3406             Putters           Blue Steel Putter  2012.0  Q1 2012
 3407    Golf Accessories         Course Pro Umbrella  2012.0  Q1 2012
 ...                  ...                         ...     ...      ...
 85667  Insect Repellents            BugShield Lotion  2014.0  Q3 2014
 85668          Sunscreen                 Sun Blocker  2014.0  Q3 2014
 85669          Sunscreen              Sun Shelter 15  2014.0  Q3 2014
 85670          Sunscreen              Sun Shelter 30  2014.0  Q3 2014
 85671          First Aid             Calamine Relief  2014.0  Q3 2014

          Revenue  Quantity  Gross margin
 3403    69057.80     214.0      0.315153
 3404    57590.85     115.0      0.445356
 3405   198666.24     290.0      0.501355
 3406    18992.50     214.0      0.535775
 3407    19082.56    1568.0      0.506984
 ...          ...       ...           ...
 85667    3381.00     483.0      0.667143
 85668    1625.00     325.0      0.610000
 85669    2519.40     510.0      0.637652
 85670    4944.10    1009.0      0.622449
 85671     408.00      68.0      0.528333

 [3639 rows x 11 columns],
 'Australia':       Retailer country Order method type     Retailer type  \
 3735         Australia         Telephone         Golf Shop
 3736         Australia         Telephone         Golf Shop
 3737         Australia         Telephone         Golf Shop
 3738         Australia         Telephone         Golf Shop
 3739         Australia         Telephone         Golf Shop
 ...                ...               ...               ...
 85862        Australia       Sales visit  Department Store
 85863        Australia       Sales visit  Department Store
 85864        Australia       Sales visit  Department Store
 85865        Australia       Sales visit  Department Store
 85866        Australia       Sales visit  Department Store

                Product line Product type                   Product    Year  \
 3735   Personal Accessories      Watches      Mountain Man Digital  2012.0
 3736   Personal Accessories   Binoculars               Seeker Mini  2012.0
 3737   Personal Accessories   Navigation               Glacier GPS  2012.0
 3738         Golf Equipment        Irons     Hailstorm Steel Irons  2012.0
 3739         Golf Equipment        Irons  Hailstorm Titanium Irons  2012.0
 ...                     ...          ...                       ...     ...
 85862  Personal Accessories      Watches      Mountain Man Digital  2014.0
 85863  Personal Accessories      Watches       Mountain Man Deluxe  2014.0
 85864  Personal Accessories      Watches  Mountain Man Combination  2014.0
 85865  Personal Accessories   Navigation             Glacier Basic  2014.0
 85866        Golf Equipment      Putters         Blue Steel Putter  2014.0

        Quarter   Revenue  Quantity  Gross margin

In [49]:
df = pd.read_csv('marathon_results_2016.csv', index_col='Bib',
 usecols=['Bib','40K','Half','Pace','Age','M/F','Country','State','City'])

In [9]:
df['40K'] = df['40K'].apply(pd.to_timedelta(errors='coerce'))
# df['Half'] = df['Half'].apply(pd.to_timedelta)

TypeError: to_timedelta() missing 1 required positional argument: 'arg'

In [50]:
df['40K'] = pd.to_timedelta(df['40K'], errors='coerce')

In [51]:
df['40K']

Bib
5       0 days 02:05:59
1       0 days 02:05:59
6       0 days 02:06:47
11      0 days 02:06:47
14      0 days 02:08:11
              ...
31985               NaT
26218   0 days 07:25:15
29403   0 days 07:54:21
30690   0 days 07:59:12
28487               NaT
Name: 40K, Length: 26630, dtype: timedelta64[ns]

In [52]:
df['Half'] = pd.to_timedelta(df['Half'], errors='coerce')
df['Half']

Bib
5       0 days 01:06:45
1       0 days 01:06:46
6       0 days 01:06:44
11      0 days 01:06:46
14      0 days 01:06:46
              ...
31985   0 days 03:40:16
26218   0 days 03:40:17
29403   0 days 03:37:49
30690   0 days 03:00:22
28487   0 days 04:47:17
Name: Half, Length: 26630, dtype: timedelta64[ns]

In [19]:
df['TotalSeconds'] = df['40K'].apply(lambda x: timedelta.total_seconds(x))

In [17]:
df.dropna(inplace=True)

In [18]:
df

,Age,M/F,City,State,Country,Half,40K,Pace
Bib,,,,,,,,
43,28,M,Dallas,TX,USA,0 days 01:07:57,0 days 02:12:47,0:05:25
21,31,M,Colorado Springs,CO,USA,0 days 01:08:24,0 days 02:14:39,0:05:26
27,30,M,New Paltz,NY,USA,0 days 01:08:48,0 days 02:16:22,0:05:32
79,40,M,Boulder,CO,USA,0 days 01:10:15,0 days 02:16:51,0:05:32
38,28,M,Wolcottville,IN,USA,0 days 01:11:40,0 days 02:19:24,0:05:37
...,...,...,...,...,...,...,...,...
26144,52,F,Justin,TX,USA,0 days 03:11:00,0 days 06:36:56,0:15:59
4358,43,M,Yardley,PA,USA,0 days 01:28:18,0 days 06:54:20,0:16:53
26218,47,F,Huntington Beach,CA,USA,0 days 03:40:17,0 days 07:25:15,0:17:51
29403,39,M,Reedsburg,WI,USA,0 days 03:37:49,0 days 07:54:21,0:19:13
30690,35,M,Franklin,TN,USA,0 days 03:00:22,0 days 07:59:12,0:19:17

In [20]:
df['HalfSeconds'] = df['Half'].apply(lambda x: timedelta.total_seconds(x))

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23761 entries, 43 to 30690
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           23761 non-null  int64
 1   M/F           23761 non-null  object
 2   City          23761 non-null  object
 3   State         23761 non-null  object
 4   Country       23761 non-null  object
 5   Half          23761 non-null  timedelta64[ns]
 6   40K           23761 non-null  timedelta64[ns]
 7   Pace          23761 non-null  object
 8   TotalSeconds  23761 non-null  float64
 9   HalfSeconds   23761 non-null  float64
dtypes: float64(2), int64(1), object(5), timedelta64[ns](2)
memory usage: 2.0+ MB

In [23]:
df.describe()

,Age,Half,40K,TotalSeconds,HalfSeconds
count,23761.000000,23761,23761,23761.000000,23761.000000
mean,42.103110,0 days 01:49:46.349227726,0 days 03:42:23.895332688,13343.895333,6586.349228
std,11.419015,0 days 00:17:51.565867043,0 days 00:38:55.501588988,2335.501589,1071.565867
min,18.000000,0 days 01:07:57,0 days 02:12:47,7967.000000,4077.000000
25%,33.000000,0 days 01:37:19,0 days 03:15:26,11726.000000,5839.000000
50%,42.000000,0 days 01:47:17,0 days 03:35:39,12939.000000,6437.000000
75%,50.000000,0 days 01:58:39,0 days 04:02:33,14553.000000,7119.000000
max,83.000000,0 days 03:40:17,0 days 07:59:12,28752.000000,13217.000000

In [24]:
df.value_counts()

Age  M/F  City         State  Country  Half             40K              Pace     TotalSeconds  HalfSeconds
39   F    Santa Clara  UT     USA      0 days 01:51:27  0 days 03:38:56  0:08:49  13136.0       6687.0         2
40   M    Gardiner     ME     USA      0 days 01:33:41  0 days 03:22:43  0:08:11  12163.0       5621.0         2
45   F    Norfolk      CT     USA      0 days 01:43:27  0 days 03:22:29  0:08:10  12149.0       6207.0         2
50   F    Wellesley    MA     USA      0 days 02:05:37  0 days 03:59:32  0:09:37  14372.0       7537.0         2
47   M    Oriskany     NY     USA      0 days 01:32:14  0 days 03:03:59  0:07:27  11039.0       5534.0         1
                                                                                                              ..
36   M    Marietta     GA     USA      0 days 01:44:32  0 days 03:25:47  0:08:18  12347.0       6272.0         1
          Marblehead   MA     USA      0 days 01:34:23  0 days 03:16:06  0:07:56  11766.0       5663.0         1
                                       0 days 01:29:37  0 days 02:57:53  0:07:12  10673.0       5377.0         1
                                       0 days 01:26:25  0 days 02:59:29  0:07:19  10769.0       5185.0         1
83   M    Tyler        TX     USA      0 days 02:14:49  0 days 04:35:50  0:11:08  16550.0       8089.0         1
Length: 23757, dtype: int64

In [25]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [26]:
df.City.value_counts()

Boston           721
New York         451
Chicago          261
Toronto          223
San Francisco    197
                ...
New Fairfield      1
Beauharnois        1
Bellport           1
Boalsburg          1
Reedsburg          1
Name: City, Length: 4475, dtype: int64

In [27]:
df.nunique()

Age               65
M/F                2
City            4475
State             67
Country            2
Half            4721
40K             8288
Pace             528
TotalSeconds    8288
HalfSeconds     4721
dtype: int64

In [28]:
df.City.unique()

array(['Dallas', 'Colorado Springs', 'New Paltz', ..., 'Olive Branch',
       'Justin', 'Reedsburg'], dtype=object)

In [55]:
citys = df.City.unique()

In [54]:
groups = {}

In [ ]:
for city in citys:
    groups[city] = df.where(df.City ==city).dropna()

In [ ]:
groups

In [ ]:
len(groups)

In [57]:
groups.keys()

dict_keys([])

In [ ]:
df.where(df.City ==city).dropna()

In [ ]:
df.City